apiVersion: apps/v1
kind: Deployment
metadata:
  name: dace-d
  labels:
    app: dace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dace
  template:
    metadata:
      labels:
        app: dace
        version: v1
    spec:
      containers:
      - name: dace
        image: dimkapro/dace:latest
        ports:
        - containerPort: 6878
          name: tv
