apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dace-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 6878
      name: tv
      protocol: HTTP  
    hosts:
    - "*" 
